Repository NeuroTechX/moabb, pull requests merged in 2021-06, with the labels that each got.

#188 Remove unused dependencies - review examples and tutorials
  examples/plot_cross_session_multiple_datasets.py
  examples/plot_cross_session_ssvep.py
  examples/plot_cross_subject_ssvep.py
  moabb/analysis/results.py
  moabb/datasets/Lee2019.py
  moabb/datasets/Weibo2014.py
  moabb/datasets/Zhou2016.py
  moabb/datasets/alex_mi.py
  moabb/datasets/bnci.py
  moabb/datasets/braininvaders.py
  moabb/datasets/download.py
  moabb/datasets/epfl.py
  moabb/datasets/gigadb.py
  moabb/datasets/mpi_mi.py
  moabb/datasets/neiry.py
  moabb/datasets/schirrmeister2017.py
  moabb/datasets/ssvep_exo.py
  moabb/datasets/ssvep_mamem.py
  moabb/datasets/ssvep_nakanishi.py
  moabb/datasets/ssvep_wang.py
  moabb/datasets/upper_limb.py
  moabb/tests/download.py
  moabb/tests/evaluations.py
  poetry.lock
  pyproject.toml
  tutorials/tutorial_1_simple_example_motor_imagery.py
  tutorials/tutorial_2_using_mulitple_datasets.py
  tutorials/tutorial_3_benchmarking_multiple_pipelines.py
Labels: dataset, documentation, enhancement

#174 ci: deploy docs from CI pipeline
  .github/workflows/docs.yml
  .github/workflows/test.yml
  README.md
  docs/source/README.md
  docs/source/conf.py
  docs/source/datasets.rst
  docs/source/paradigms.rst
  docs/source/pipelines.rst
  examples/advanced_examples/README.txt
  examples/advanced_examples/plot_filterbank_csp_vs_csp.py
  examples/advanced_examples/plot_mne_and_scikit_estimators.py
  examples/advanced_examples/plot_select_electrodes_resample.py
  examples/advanced_examples/plot_statistical_analysis.py
  examples/external/README.txt
  examples/external/plot_learning_curve_p300_external.py
  examples/learning_curve/README.txt
  examples/learning_curve/plot_learning_curve_motor_imagery.py
  examples/learning_curve/plot_learning_curve_p300.py
  examples/plot_cross_session_motor_imagery.py
  examples/plot_cross_session_multiple_datasets.py
  examples/plot_cross_subject_ssvep.py
  examples/plot_explore_paradigm.py
  examples/plot_within_session_p300.py
  moabb/analysis/meta_analysis.py
  moabb/analysis/plotting.py
  moabb/datasets/base.py
  moabb/datasets/bbci_eeg_fnirs.py
  moabb/datasets/bnci.py
  moabb/datasets/braininvaders.py
  moabb/datasets/download.py
  moabb/datasets/neiry.py
  moabb/datasets/physionet_mi.py
  moabb/datasets/schirrmeister2017.py
  moabb/datasets/ssvep_exo.py
  moabb/datasets/ssvep_mamem.py
  moabb/datasets/ssvep_nakanishi.py
  moabb/datasets/ssvep_wang.py
  moabb/datasets/utils.py
  moabb/pipelines/csp.py
  moabb/pipelines/features.py
  tutorials/plot_Getting_Started.py
  tutorials/tutorial_1_simple_example_motor_imagery.py
  tutorials/tutorial_2_using_mulitple_datasets.py
  tutorials/tutorial_3_benchmarking_multiple_pipelines.py
  tutorials/tutorial_4_adding_a_dataset.py
Labels: documentation, enhancement

#195 Allow changing of storage location
  moabb/datasets/bnci.py
  moabb/datasets/download.py
  moabb/datasets/physionet_mi.py
  moabb/datasets/ssvep_exo.py
  moabb/datasets/ssvep_mamem.py
  moabb/utils.py
Labels: enhancement, medium

#198 Broadening subject_list type
  moabb/datasets/base.py
Labels: easy, enhancement

#207 Remove update_path from data_dl
  moabb/__init__.py
  moabb/datasets/Lee2019.py
  moabb/datasets/Weibo2014.py
  moabb/datasets/Zhou2016.py
  moabb/datasets/alex_mi.py
  moabb/datasets/base.py
  moabb/datasets/bbci_eeg_fnirs.py
  moabb/datasets/gigadb.py
  moabb/datasets/mpi_mi.py
  moabb/datasets/schirrmeister2017.py
  moabb/datasets/ssvep_mamem.py
  moabb/datasets/ssvep_nakanishi.py
  moabb/datasets/ssvep_wang.py
  moabb/datasets/upper_limb.py
  moabb/tests/download.py
  pyproject.toml
Labels: bug
