Repository NeuroTechX/moabb, pull requests merged in 2021-08, with the labels that each got.

#217 Adding ERP and SSVEP parts of Lee2019
  docs/source/datasets.rst
  docs/source/whats_new.rst
  moabb/datasets/Lee2019.py
  moabb/datasets/__init__.py
Labels: enhancement, dataset

#218 Add whats new and docs recommandation in contributing page.
  CONTRIBUTING.md
  docs/source/whats_new.rst
Labels: documentation

#222 Avoid leaking information between sessions
  .github/workflows/test-devel.yml
  CONTRIBUTING.md
  docs/source/whats_new.rst
  moabb/evaluations/evaluations.py
Labels: bug
