Repository NeuroTechX/moabb, pull requests merged in 2023-01, with the labels that each got.

#264 Benchmark function
  README.md
  docs/source/README.md
  docs/source/whats_new.rst
  examples/README.txt
  examples/advanced_examples/README.txt
  examples/plot_benchmark.py
  examples/sample_pipelines/CSP_SVM.yml
  examples/sample_pipelines/TSLR.yml
  moabb/__init__.py
  moabb/analysis/__init__.py
  moabb/analysis/meta_analysis.py
  moabb/benchmark.py
  moabb/datasets/__init__.py
  moabb/datasets/download.py
  moabb/datasets/fake.py
  moabb/paradigms/base.py
  moabb/paradigms/motor_imagery.py
  moabb/paradigms/p300.py
  moabb/paradigms/ssvep.py
  moabb/pipelines/utils.py
  moabb/run.py
  moabb/tests/__init__.py
  moabb/tests/benchmark.py
  moabb/tests/test_pipelines/CSP.yml
Labels: enhancement, documentation

#318 Fix dataset downloading errors
  docs/source/whats_new.rst
  moabb/datasets/bnci.py
  moabb/datasets/download.py
  moabb/datasets/huebner_llp.py
  scripts/data_visualization_p300.py
Labels: bug, dataset

#302 Return raw with get_data
  moabb/evaluations/base.py
  moabb/evaluations/evaluations.py
  moabb/paradigms/base.py
  moabb/paradigms/p300.py
  moabb/tests/paradigms.py
Labels: enhancement
